// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eabgdxhmfyuioblanysb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhYmdkeGhtZnl1aW9ibGFueXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjU2ODQsImV4cCI6MjA5MDA0MTY4NH0.HRjMFarTFle8NnIN8owXo0kZffQ5m8SsGGXCNqQrH5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});